### ISSUE TITLE
Erreur

### ISSUE THREAD

**Issue by Atarea** [Ecilam/BloodWarsAnalyseRC#1]
A chaque RC de combat j'ai cette erreur qui s'affiche 
'Le nom de ce vampire doit être lié à son ID. Merci de consulter la salle du Trone pour rendre ce script opérationnel'...
Sauf que ca fait des milliers de fois que je vais en salle du Trone... Ca fonctionnait parfaitement avant je ne comprends pas...

**Comment by Ecilam** [comment]
En effet, l'équipe BW a modifié le code pour afficher le nom du serveur et du coup le script ne retrouvait plus l'info. 
Bug corrigé avec la version 2017-04-11.
