### ISSUE TITLE
Unable to link vampire name and ID

### ISSUE THREAD

**Issue by akhlan** [Ecilam/BloodWarsAnalyseRC#2]
Hello,

when I want to use BloodWarsAnalyseRC, I get an error message

`      "sUnknowID": ["BloodWarsAnalyseRC - Erreur :\n\nLe nom de ce vampire doit être lié à son ID. Merci de consulter la Salle du Trône pour rendre le script opérationnel.\nCe message est normal si vous utilisez ce script pour la première fois ou si vous avez changé le nom du vampire.",`

I did not change the name of my vampire and I went to the throne room...

How to solve this problem?

I tested under Chrome and Firefox

Thanks
Akhlan

**Comment by akhlan** [comment]
Salut,

je pensais que tu étais Anglais ;) le serveur est le R8 Moria S5 et mon pseudo, Akhlan

**Comment by Ecilam** [comment]
Même si je n'ai pas reproduit j'ai constaté que le script s'activait par erreur sur la page de login. Je viens de le corriger.

Juste pour être sûr, tu n'utilises pas dans les options du jeu la Texture graphique Awakening car mes scripts ne sont pas compatibles avec ?

**Comment by akhlan** [comment]
Si c'était mon skin qui posait problème.... Par contre, Awakening propose des options que l'on ne retrouve pas, je ne sais pas quoi garder encore entre tes scripts et le thème.... À suivre....

**Comment by Ecilam** [comment]
Avec cette texture la partie analyse semble bien fonctionner mais le script échoue à retrouver le nom et le royaume du joueur.
Si ce n'est que ça je regarderai ce week-end pour une solution.

**Comment by Ecilam** [comment]
Correction faite

**Comment by akhlan** [comment]
presque :D On a encore l'erreur (enfin j'ai....) dans le menu "Le puit des âmes" / "Synthèse des objets"

**Comment by akhlan** [comment]
Autant pour moi, ce n'est pas sur BloodWarsAnalyseRC mais sur Blood Wars Mix, je te fais un ticket là bas ou tu t'en occupes d'ici ?

**Comment by Ecilam** [comment]
Il est plus que probable que cette erreur vienne plutôt de BloodWarsMix. Je peux faire en sorte que cette pop-in disparaisse mais l'interface ne s'affichera pas pour autant car la texture Awakening est très différente des versions classiques.
N'ayant pas le temps d'y regarder actuellement je ne peux que conseiller de désactiver ce script si tu souhaites utiliser cette texture.

**Comment by akhlan** [comment]
C'est ce que j'ai fait, merci ;)

**Comment by Ecilam** [comment]
Je viens de mettre à jour BloodWarsMix pour logiquement corriger ce problème :)

**Comment by akhlan** [comment]
effectivement, je n'ai plus le message d'erreur après la mise à jour, merci ;)
